development:
  adapter: postgresql
  encoding: utf8
  database: glaceon_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: glaceon_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: glaceon_production
  pool: 5
  username:
  password: